<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WKSWUPUN0946" ignored="0" name="Gradle test" tests="1" failures="1" timestamp="05 Mar 2020 11:09:34 GMT" time="24.944" errors="0">
  <testcase name="successfulPaymentFlow" time="13.16" classname="com.dk.ui.TestOrder">
    <failure type="java.lang.AssertionError" message="card number doesn&amp;apos;t matched expected [4811111111111114] but found [4811111114]">
      <![CDATA[java.lang.AssertionError: card number doesn't matched expected [4811111111111114] but found [4811111114]
at com.dk.ui.PaymentConfirmationPage.verifyPaymentDetails(PaymentConfirmationPage.java:57)
at com.dk.ui.TestOrder.successfulPaymentFlow(TestOrder.java:38)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- successfulPaymentFlow -->
</testsuite> <!-- Gradle test -->
